- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/tags
  value:
    description: |-
      A list of tags that will be assigned to the resource in NetBox.
      Each tag may contain either the `name` or `slug` field (one of them is required).
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          description: name of the tag
        slug:
          type: string
          description: slug of the tag
      x-kubernetes-validations:
        - message: One of the fields `name` or `slug` must be set
          rule: has(self.name) || has(self.slug)
    example:
      - name: tag1
      - slug: tag2